### ISSUE TITLE
DataSource

### ISSUE THREAD

**Issue by gravity1989** [mbhenaff/spectral-lib#5]
Has someone downloaded any dataset and got it to work?

I am just wondering if what is the right dataset to download and use?

**Comment by gravity1989** [comment]
Solved for the cifar dataset/

**Comment by Conchylicultor** [comment]
Can you help me on how did you run the program with cifar ? 
When loading the dataset, the program is looking for a cifar_10_norm.th file but this one was not present on the downloaded dataset ( only some data_batch_X.t7 files). I did try to train with one of those files but I've got a 'unkown object' error.

How do you generate the cifar_10_norm.th file ?

**Comment by gravity1989** [comment]
Hi,

The file is not present. Instead as mentioned in another issue, you have to
manually download the cifar datasets and generate the laplacian using the
Matlab scripts.

On Thu, Mar 31, 2016 at 5:10 PM, Conchylicultor notifications@github.com
wrote:

> Can you help me on how did you run the program with cifar ?
> When loading the dataset, the program is looking for a cifar_10_norm.th
> file but this one was not present on the downloaded dataset ( only some
> data_batch_X.t7 files). I did try to train with one of those files but I've
> got a 'unkown object' error.
> 
> How do you generate the cifar_10_norm.th file ?
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/mbhenaff/spectral-lib/issues/5#issuecomment-203891456

## 

Regards,
R.V.

**Comment by Conchylicultor** [comment]
Thank you for your answer. I understand we need to generate something but how this be done ? 

By looking at the code, in order to generate the laplacian, it require 'cifar-10-batches-t7/trdata.mat' which also does not exist. **How do you obtain this file ?**

Then, according to the script 'build_laplacian.m' the graphs are saved under the name 'cifar_laplacian_poolsize_XX_stride_YY_neighbs_ZZ.mat'. Using the script 'convert_to_torch.lua', it seems that we can save it into '.th'. **Is it this file we need to rename cifar_10_norm.th and use as training ?**

**Comment by gravity1989** [comment]
I will give you a quick answer. My friend did the laplacian part.

He downloaded the matlab version of cifar files, used the
build_graph_laplacian.m to generate the laplacian. Oncet the
'cifar_laplacian_poolsize_XX_stride_YY_neighbs_ZZ.mat' file is obtained,
try to place it in the location where the code is looking for the laplacian.

On Thu, Mar 31, 2016 at 6:59 PM, Conchylicultor notifications@github.com
wrote:

> Thank you for your answer. I understand we need to generate something but
> how this be done ?
> 
> By looking at the code, in order to generate the laplacian, it require
> 'cifar-10-batches-t7/trdata.mat' which also does not exist. _How do you
> obtain this file ?_
> 
> Then, according to the script 'build_graph_laplacian.m' the graphs are
> saved under the name
> 'cifar_laplacian_poolsize_XX_stride_YY_neighbs_ZZ.mat'. Using the script
> 'convert_to_torch.lua', it seems that we can save it into '.th'. _Is it
> this file we need to rename cifar_10_norm.th http://cifar_10_norm.th and
> use as training ?_
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/mbhenaff/spectral-lib/issues/5#issuecomment-203935989

## 

Regards,
R.V.

**Comment by Conchylicultor** [comment]
So I did generate the laplacien which in this case seems to be a 1024*1024 matrix. But it does not solve the original problem of how to obtain the `cifar_10_norm.th` training file which should contain the data and labels.

**Comment by gravity1989** [comment]
You will have to write code to instead read the cifar  dataset manually.
You can use some code for that from here.

You will have to set the train_set.data etc.
I am unable to paste the code as I am using my office computer.

On Thu, Mar 31, 2016 at 10:51 PM, Conchylicultor notifications@github.com
wrote:

> So I did generate the laplacien witch in this case seems to be a 1024*1024
> matrix. But it does not solve the original problem of how to obtain the
> cifar_10_norm.th training file which should contain the data and labels.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/mbhenaff/spectral-lib/issues/5#issuecomment-204034161

## 

Regards,
R.V.

**Comment by Conchylicultor** [comment]
I'm struggling with it. Could you show me the code you use. It would be
really nice
